theme: jekyll-theme-dinky
title: EZType's homepage
description: A portfolio highlighting my projects, technical skills, and professional growth by demonstrating my experience through projects, code, and documentation.
